config/routes.rb
DBMap::Application.routes.draw do
  resources :apps

  resources :environments

  resources :hostings do
    collection do
      match 'search' => 'hostings#search', :via => [:get, :post], :as => :search
    end
  end 
   resources :databases do 
 collection do
      match 'search' => 'databases#search', :via => [:get, :post], :as => :search
      match 'dataview' => 'databases#dataview',:via => [:get,:post]
      match 'db_search' => 'databases#db_search',:via => [:get,:post], :as => :db_search
     match '/db_search_view' => "databases#db_search_view"
    end

  end
   post '/options' => 'databases#options'
     match 'view_report' => 'databases#view_report'

   resources :fields do
    collection do
      match 'search' => 'fields#search', :via => [:get, :post], :as => :search
    end
   end 
   resources :tables do
    collection do
      match 'search' => 'tables#search', :via => [:get, :post], :as => :search
    end
   end 
  resources :schemas
  resources :pages
  post "pdf_report"=>"databases#pdf_report"
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login' => 'sessions#new', as: :login
  get 'signup' => 'users#new', as: :signup
  get 'account' => 'users#edit', as: :account
  get '/admin' => 'admin/categories#index'
  match '/download_single_pattern/:id' => "patterns#download_single_pattern"
  match '/download_patterns' => "patterns#download_patterns"
  match '/database_schema' => "databases#database_schema"
  match '/block_tree_view' => "databases#block_tree_view"
  match '/database_schema1' => "databases#database_schema1"
  resources :users, except: :destroy
  resources :sessions, only: [:new, :create, :destroy]
  resources :patterns
match '/db_data_view' => "databases#db_data_view"

  namespace :admin do
    resources :users, except: [:show]
    resources :categories do
      collection { post :sort }
    end
    root to: "home#index"  
  end
  root to: "home_page#index"
  match '/privacy' => 'pages#privacy'
  match '/contact_us' => 'pages#new'
  match '/legal'=> 'pages#legal'
  match '/pricing' => 'pages#pricing'

end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_filter :authorize
  # GET /tables
  # GET /tables.json
=begin
  def index
 # @databases = current_user.organization.databases.page(params[:page]).per(30)
  @q  = current_user.organization.tables.search(params[:q])
    #@databases = current_user.organization.databases
    #@q = @databases.tables.search(params[:q])
    @tables =  @q.result.page(params[:page]).per(30)
    #@tables = @q.result(:distinct  => true).find(:all,:order=>"updated_at DESC")
    #@tables = @q.result().find(:all,:order=>"updated_at DESC")
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tables }
    end
  end
=end
  def index

  if params[:table]
   if params[:table]["db_datab"] != "All"
    @q = current_user.organization.tables.where(:database_name => params[:table]["db_datab"]).search(params[:q])
  else
    @q  = current_user.organization.tables.search(params[:q])
  end
    @tables =  @q.result.page(params[:page]).per(30)
  else
    @q  = current_user.organization.tables.search(params[:q])
    @tables =  @q.result.page(params[:page]).per(30)
    #@tables = @q.result(:distinct  => true).find(:all,:order=>"updated_at DESC")
    #@tables = @q.result().find(:all,:order=>"updated_at DESC")
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tables }
    end
 end


   end
  # GET /tables/1
  # GET /tables/1.json
  def show
    #@table = current_user.organization.tables.find(params[:id])
    @table = Table.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @table }
    end
  end

  # GET /tables/new
  # GET /tables/new.json
  def new
    @table = Table.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @table }
    end
  end

  # GET /tables/1/edit
  def edit
    @table = Table.find(params[:id])
  end

  # POST /tables
  # POST /tables.json
  def create
    @table = Table.new(params[:table])
    @table.organization = current_user.organization
    @table.user = current_user

    respond_to do |format|
      if @table.save
        format.html { redirect_to @table, notice: 'Table was successfully created.' }
        format.json { render json: @table, status: :created, location: @table }
      else
        format.html { render action: "new" }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tables/1
  # PUT /tables/1.json
  def update
    @table =Table.find(params[:id])

    respond_to do |format|
      if @table.update_attributes(params[:table])
        format.html { redirect_to @table, notice: 'Table was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1
  # DELETE /tables/1.json
  def destroy
    @table = current_user.organization.tables.find(params[:id])
    @table.destroy

    respond_to do |format|
      format.html { redirect_to tables_url }
      format.json { head :no_content }
    end
  end
  def search

    @q = current_user.organization.tables.search(params[:q])
    if params[:q]
      @tables = @q.result#(:distinct  => true).find(:all,:order=>"updated_at DESC")
    end
    
    respond_to do |format|
      format.html
      format.json { head :no_content }
    end
  end

  
end

app/views/tables/_form.html.erb
<%= simple_form_for(@table, :html=>{:multipart => true, class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
<%#= text_field_tag :something, f., :readonly => true %>
    <%= f.input :table_name,:readonly => true %>
 <%= f.input :database_name,:readonly => true %>

<%= f.input :environment,as: :select,collection: current_user.organization.environments.select(:db_environment_name).map{|x|x.db_environment_name},:prompt => "Select Environment" %>
    <%#= f.input :database %>
 <%= f.input :short_description,:label => 'Description', input_html: {rows: '2',cols: '2', class: 'span6'} %>

    <%= f.input :table_type, as: :select, collection: ['Maintenance','Recap','Setup','Transactional','View'], :prompt => "Select Type" ,:label =>'Table Type' %>
  <%#= f.input :feature_types, as: :select, collection: ['Feature','Section','Module'], :prompt => "Select Type" ,:label =>'Feature/Section/Module' %>
 <%= f.input :feature_types, :label =>'Feature/Section/Module' %>
    

    <%=  f.input :top_used, as: :boolean,:label =>'Top Used Table' %>
   <%= f.input :description,:label => 'Long Description', input_html: {rows: '5',cols: '3', class: 'span9'} %>

  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/tables/_menu.html.erb
<ul class="nav nav-tabs">
  <li class="<%= action_active('index') %>">
    <%= link_to tables_path do %>
        <i class="icon-list-alt"></i>
        Index
    <% end %>
  </li>

  <li class="<%= action_active('new') %>">
    <%= link_to new_table_path do %>
      <i class="<%= green_icon %>"></i>
      Create New Record
    <% end %>
  </li>
</ul>

app/views/tables/_search_form.html.erb
 <script type="text/javascript">
	$(function() {
		// Datepicker
		$('#datepicker').datepicker({
			//inline: true
			dateFormat : 'mm/dd/yy'
		});
	$('#table_db_datab').change(function(){
			$(this).closest('form').submit();
			});


	}); 
</script>

<div id="simple-search-form">
	<%= search_form_for q,:url => search_tables_path, :html => {method: :post, class: 'well form-search'}  do |f| %>
	<fieldset>
		<%= f.text_field :environment_or_database_name_or_table_name_or_description_cont, class: "input-medium search-query" %>
		<button type="submit" class="btn">
			Search
		</button>
		&nbsp;&nbsp; <a href="#" id="advance-search">Advance</a>
		<% end %>
	</fieldset>
	<div style="float:right;margin-top:-70px;margin-right:35px">
	 <%= simple_form_for :table,:url => url_for(:action=>'index',:controller=>'tables'), method: :get,:html => {class: 'form-horizontal '}  do |f| %>
		 <%= f.input :db_datab, as: :select, collection: Database.select(:db_name).map{|x| x.db_name}.insert(0,"All"), :prompt => "Select Database" ,:label =>'Database' %>

	<% end %>
      </div>
</div>

<div id="advance-search-form" style="display: none">
	<%= search_form_for q,:url => search_tables_path, :html => {method: :post, class: 'form-horizontal'}  do |f| %>
	<fieldset>
		<legend>
			Search Table
		</legend>
		<div class="control-group">
			<%= f.label :environment_cont, "Environment", class: 'control-label' %>
			<div class="controls">
				<%= f.text_field :environment_cont %>
			</div>
		</div>

		<div class="control-group">
			<%= f.label :database_name_cont, "Database", class: 'control-label' %>
			<div class="controls">
				<%= f.text_field :database_name_cont %>
			</div>
		</div>

		<div class="control-group">
			<%= f.label :ofrows_eq, "Of Rows", class: 'control-label' %>
			<div class="controls">
				<%= f.text_field :ofrows_eq %>
			</div>
		</div>
		<div class="control-group">
			<%= f.label :ofcolumns_eq, "Of Columns", class: 'control-label' %>
			<div class="controls">
				<%= f.text_field :ofcolumns_eq%>
			</div>
		</div>

		<div class="form-actions">
			<%= f.submit class: 'btn btn-primary' %>
			<input type="reset" class='btn'>
			</input>
			<a href="#" id="advance-search">Simple</a>
		</div>
	</fieldset>
	<% end %>
</div>

app/views/tables/edit.html.erb
<h1>Editing table</h1>

<%= render 'form' %>

<%= link_to 'Show', @table %> |
<%= link_to 'Back', tables_path %>

app/views/tables/index.html.erb
   
<%#= render :partial => "menu" %>
<!--Search block-->
<% if !@tables.nil? %>
<%= render :partial => "tables/search_form", locals: {q: @q} %>
<% end %> <!--Search block-->
<% if @tables.blank? %>
  <div class="well">You don't currently have any tables </div>
<% else %>
<h1>Tables</h1>
<!--Displaying table values from db-->
<table class="table table-striped" >
	<tr>

    <th><%=sort_link(@q,:database_name,"Database" )%></th>
    <th></th>
     <th><%= sort_link(@q, :table_name, "Table Name") %></th>
    <th><%= sort_link(@q, :ofrows, "Of Rows") %></th>
      <th><%= sort_link(@q, :ofcolumns, "Of Columns") %></th>
    <th><%= sort_link(@q, :updated_at, "Last Used") %></th>
		 <th><%= sort_link(@q, :environment, "Environment") %></th>
  <th><%= sort_link(@q, :description, "Description") %></th>
    <th></th>
  </tr>
  <%# @databases.each do |database| %>
<% @tables.each do |table| %>
  <tr>

    <td ><%= table.database_name %></td>
<td>  <%= link_to image_tag("exp.png", :border => 0), '#',:title =>"Expand Table fields",:class => "expand " ,:id => "#{table.id }" %>
  <%= link_to image_tag("colp.png", :border => 0) , '#',:class => "collapse",:style =>"display:none;" ,:id => "#{table.id }"%></td>
    
            <td><%= table.table_name %></td>
    <td><%= table.ofrows %></td>
    <td><%= table.ofcolumns %></td>
    <td><%= table.updated_at.strftime("%b-%d-%Y") if !table.updated_at.blank? %></td>
    <td><%= table.environment %></td>
    <td><%= table.short_description %></td>
   <td style="width:140px;">
 
   <%#= link_to 'Table Link', table, class: 'btn btn-mini' %>
   <%= link_to 'Edit', edit_table_path(table), class: 'btn btn-mini' %>

 </td>
  </tr>

<tr  class="<%= table.id %>">
<td class="<%= table.id %>" colspan="2" style="display:none;"></td>
<td  class="<%= table.id %>" colspan="8" style="display:none;"><b> Fields: </b></td>

</tr>
<% table.fields.each do |f| %>
<tr class="<%= table.id %>" >
<td class="<%= table.id %>" colspan="2" style="display:none;background-color:white;"></td>
<td  colspan="8"  class="<%= table.id %>" style="display:none;background-color:white;"> <%= f.field_name %></td>
</tr>
<% end %>
<% end %>
<% #end %>

</table>
<%= paginate @tables  %>
<% end %>

app/views/tables/new.html.erb
<%= render :partial => "menu" %>

<%= render 'form' %>

<%#= link_to 'Back', tables_path %>

app/views/tables/search.html.erb
<%= render :partial => "search_form", locals: {q: @q} %>
<div id="search-result">
  <% if @tables.blank? %>
    <% if params[:q] %>
      <p class="well">No records found</p>
	    <% else %>
		    <p>Your search does not generate a result</p>
    <% end %>
  <% else %>
  <div style="float:right;margin-right:20px;"><% unless @tables.blank? %>[<%= @tables.count %>] Records Found<% end %></div>
<br/>
<table class="table table-striped" >
	<tr>

    <th><%=sort_link(@q,:database_name,"Database" )%></th>
     <th><%= sort_link(@q, :table_name, "Table Name") %></th>
    <th><%= sort_link(@q, :ofrows, "Of Rows") %></th>
      <th><%= sort_link(@q, :ofcolumns, "Of Columns") %></th>
    <th><%= sort_link(@q, :updated_at, "Last Used") %></th>
		 <th><%= sort_link(@q, :environment, "Environment") %></th>
  <th><%= sort_link(@q, :description, "Description") %></th>
    <th></th>
  </tr>
  <%# @databases.each do |database| %>
<% @tables.each do |table| %>
  <tr>
    <td ><%= table.try(:database).db_name %></td>
    
            <td><%= table.table_name %></td>
    <td><%= table.ofrows %></td>
    <td><%= table.ofcolumns %></td>
    <td><%= table.updated_at.strftime("%b-%d-%Y") if !table.updated_at.blank? %></td>
    <td><%= table.environment %></td>
    <td><%= table.description %></td>
   <td style="width:140px;">
   <%= link_to image_tag("exp.png", :border => 0), '#',:title =>"Expand Table fields",:class => "expand " ,:id => "#{table.id }" %>
  <%= link_to image_tag("colp.png", :border => 0) , '#',:class => "collapse",:style =>"display:none;" ,:id => "#{table.id }"%>
   <%= link_to 'Table Link', table, class: 'btn btn-mini' %>
   <%= link_to 'Edit', edit_table_path(table), class: 'btn btn-mini' %>

 </td>
  </tr>

<tr  class="<%= table.id %>">
<td  class="<%= table.id %>" colspan="8" style="display:none;"><b> Fields: </b></td>
</tr>
<% table.fields.each do |f| %>
<tr class="<%= table.id %>" >
<td  colspan="8"  class="<%= table.id %>" style="display:none;background-color:white;"> <%= f.field_name %></td>
</tr>
<% end %>
<% end %>
<% #end %>

</table>
<%#= paginate @tables  %>
<% end %>
</div>

app/views/tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Environment:</b>
  <%= @table.environment %>
</p>

<p>
  <b>Database:</b>
  <%= @table.database_name %>
  </p>
  <p>
  <b>Table Name:</b>
  <%= @table.table_name %>
</p>

<p>
  <b>Table Type:</b>
  <%= @table.table_type %>
</p>

<p>
  <b>Description:</b>
  <%= @table.description %>
</p>

<p>
  <b>Ofrows:</b>
  <%= @table.ofrows %>
</p>

<p>
  <b>Ofcolumns:</b>
  <%= @table.ofcolumns %>
</p>

<%= link_to 'Edit', edit_table_path(@table), class: 'btn' %>
<%#= link_to 'Delete', table_path(@table), method: :delete, confirm: "Are you sure?", class: 'btn btn-danger' %>
<%= link_to 'Back', tables_path, class: 'btn' %>