config/routes.rb
DBMap::Application.routes.draw do
  resources :apps

  resources :environments

  resources :hostings do
    collection do
      match 'search' => 'hostings#search', :via => [:get, :post], :as => :search
    end
  end 
   resources :databases do 
 collection do
      match 'search' => 'databases#search', :via => [:get, :post], :as => :search
      match 'dataview' => 'databases#dataview',:via => [:get,:post]
      match 'db_search' => 'databases#db_search',:via => [:get,:post], :as => :db_search
     match '/db_search_view' => "databases#db_search_view"
    end

  end
   post '/options' => 'databases#options'
     match 'view_report' => 'databases#view_report'

   resources :fields do
    collection do
      match 'search' => 'fields#search', :via => [:get, :post], :as => :search
    end
   end 
   resources :tables do
    collection do
      match 'search' => 'tables#search', :via => [:get, :post], :as => :search
    end
   end 
  resources :schemas
  resources :pages
  post "pdf_report"=>"databases#pdf_report"
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login' => 'sessions#new', as: :login
  get 'signup' => 'users#new', as: :signup
  get 'account' => 'users#edit', as: :account
  get '/admin' => 'admin/categories#index'
  match '/download_single_pattern/:id' => "patterns#download_single_pattern"
  match '/download_patterns' => "patterns#download_patterns"
  match '/database_schema' => "databases#database_schema"
  match '/block_tree_view' => "databases#block_tree_view"
  match '/database_schema1' => "databases#database_schema1"
  resources :users, except: :destroy
  resources :sessions, only: [:new, :create, :destroy]
  resources :patterns
match '/db_data_view' => "databases#db_data_view"

  namespace :admin do
    resources :users, except: [:show]
    resources :categories do
      collection { post :sort }
    end
    root to: "home#index"  
  end
  root to: "home_page#index"
  match '/privacy' => 'pages#privacy'
  match '/contact_us' => 'pages#new'
  match '/legal'=> 'pages#legal'
  match '/pricing' => 'pages#pricing'

end

app/views/apps/_form.html.erb
<%= simple_form_for @app, :html => {class: 'form-horizontal', :multipart => true  }  do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name , :label => "App Name" %>
    <%= f.input :technology %>
    <%= f.input :app_desc,:label => "Description" ,input_html: {rows: '5', class: 'span7'}%>
  </div>

  <div class="form-actions">
    <%= f.button :submit ,class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/apps/_menu.html.erb
<ul class="nav nav-tabs">
  <li class="<%= action_active('index') %>">
    <%= link_to apps_path do %>
        <i class="icon-list-alt"></i>
        Index
    <% end %>
  </li>
  
  <li class="<%= action_active('new') %>">
    <%= link_to new_app_path do %>
      <i class="<%= green_icon %>"></i>
      Create App
    <% end %>
  </li>
</ul>

app/views/apps/_result.html.erb
<table class="table table-striped">
  <tr>
    <th>App name</th>
    <th>Technology</th>
    <th>Description</th>
    <th></th>
  </tr>

<% @apps.each do |app| %>
  <tr>
    <td><%= app.name %></td>
    <td><%= app.technology %></td>
    <td><%= app.app_desc %></td>
    <td><%= link_to 'Show', app , class: 'btn btn-mini'%>
    <%= link_to 'Edit', edit_app_path(app), class: 'btn btn-mini' %>
    <%= link_to 'Destroy', app, confirm: 'Are you sure?', method: :delete, class: 'btn btn-mini btn-danger' %></td>
  </tr>
<% end %>
</table>

app/views/apps/edit.html.erb
<%= render 'menu' %>
<h1>Editing app</h1>

<%= render 'form' %>

app/views/apps/index.html.erb
<%= render :partial => "menu" %>
<h1> Apps </h1>
<% if @apps.blank? %>
 <div class="well">
   Currently you don't have any Apps.
 </div>
 <% else %>
<%= render 'result' %>
<% end %>

app/views/apps/new.html.erb
<%= render 'menu' %>
<%= render 'form' %>

app/views/apps/show.html.erb
<%= render :partial => 'menu' %>

<p>
  <b>App name:</b>
  <%= @app.name %>
</p>

<p>
  <b>Technology:</b>
  <%= @app.technology %>
</p>

<p>
  <b>Description:</b>
  <%= simple_format(@app.app_desc) %>
</p>

<br/>

<%= link_to 'Edit', edit_app_path(@app) , class: 'btn btn-mini' %> 
<%= link_to 'Delete', @app ,confirm: "Are you sure?", method: :delete  ,class: 'btn btn-mini btn-danger'%>
<%= link_to 'Back', apps_path , class: 'btn btn-mini' %>