config/routes.rb
DBMap::Application.routes.draw do
  resources :apps

  resources :environments

  resources :hostings do
    collection do
      match 'search' => 'hostings#search', :via => [:get, :post], :as => :search
    end
  end 
   resources :databases do 
 collection do
      match 'search' => 'databases#search', :via => [:get, :post], :as => :search
      match 'dataview' => 'databases#dataview',:via => [:get,:post]
      match 'db_search' => 'databases#db_search',:via => [:get,:post], :as => :db_search
     match '/db_search_view' => "databases#db_search_view"
    end

  end
   post '/options' => 'databases#options'
     match 'view_report' => 'databases#view_report'

   resources :fields do
    collection do
      match 'search' => 'fields#search', :via => [:get, :post], :as => :search
    end
   end 
   resources :tables do
    collection do
      match 'search' => 'tables#search', :via => [:get, :post], :as => :search
    end
   end 
  resources :schemas
  resources :pages
  post "pdf_report"=>"databases#pdf_report"
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login' => 'sessions#new', as: :login
  get 'signup' => 'users#new', as: :signup
  get 'account' => 'users#edit', as: :account
  get '/admin' => 'admin/categories#index'
  match '/download_single_pattern/:id' => "patterns#download_single_pattern"
  match '/download_patterns' => "patterns#download_patterns"
  match '/database_schema' => "databases#database_schema"
  match '/block_tree_view' => "databases#block_tree_view"
  match '/database_schema1' => "databases#database_schema1"
  resources :users, except: :destroy
  resources :sessions, only: [:new, :create, :destroy]
  resources :patterns
match '/db_data_view' => "databases#db_data_view"

  namespace :admin do
    resources :users, except: [:show]
    resources :categories do
      collection { post :sort }
    end
    root to: "home#index"  
  end
  root to: "home_page#index"
  match '/privacy' => 'pages#privacy'
  match '/contact_us' => 'pages#new'
  match '/legal'=> 'pages#legal'
  match '/pricing' => 'pages#pricing'

end

app/controllers/databases_controller.rb
require 'date'
require 'sqlite3'
include ActionView::Helpers::NumberHelper
class DatabasesController < ApplicationController
skip_before_filter :verify_authenticity_token
  @@pdf ="k"
  before_filter :authorize
        def index
        params[:q] = {s: 'group asc'}.merge(params[:q] || {})
           if params[:app].present?
             @app = App.find(params[:app])
             params[:q][:app_id_eq] = @app.id
           end 
	  if params[:object]
	        @obj = params[:object]
#	    @pdf = @@pdf
           if params[:list_v]
		@listv = true
	    end
         end

	  if params[:put_data]
              send_data @@pdf.render, filename: "#{params[:put_data]}.pdf", type: "application/pdf",disposition: "attachment"
	  else
    if current_user.admin?
    @q = current_user.organization.databases.search(params[:q])  
    @databases = @q.result
    #@databases = current_user.organization.databases
    else
     @databases = current_user.databases
    end 
   @apps = current_user.organization.apps
   respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @databases }
    end
end
  end
  

 def options
	  @database =params[:ids]
  render :partial => "options", :layout => false
 end
  def view_report
	 
   @document = current_user.organization.databases.find(params[:put_datas].to_i)
   
   @type = params[:type]
   @fields1 = params[:fields]
   @data = params[:data]
   @not_used = params[:not_used]
  @@pdf = ReportPdf.new(@document,@type,@fields1,@data,@not_used)
  redirect_to databases_url(:object => @document.db_name,:list_v => true)

  end

  
  
  def show
    @database = current_user.organization.databases.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @database }
    end
  end
  def new
    @database = Database.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @database }
    end
  end

  def edit
    @database = current_user.organization.databases.find(params[:id])
  end

 def create
    @app = sanitized_app(params[:database])
    @database = Database.new(params[:database])
    @database.organization = current_user.organization
    @database.user = current_user
    @database.app = @app
    data = Database.class_eval("@@synchronize").call("Mysql",params[:database][:db_connection_string],"create_tables","current_database") if params[:database][:db_technology]== "MySQL" 
  
#************creation od DB's based on technology******************
    respond_to do |format|
      if @database.save
         #render :text => params.inspect and return
	       if  params[:database][:db_technology]== "Sqlite"
              data =  get_sqlite_schema(@database)
             render :text => data and return
	         if  data.class != String && !data.nil? 
			msg = update_sqlite_schema(data,@database)
			 @database.update_attributes(:last_sync => Date.today)
                  format.html { redirect_to @database, notice: 'Database was successfully created.' }
		else
		@database.destroy
                format.html { redirect_to @database, notice: "#{msg}" }

	         end
	       else
	        if data.class != String && !data.nil? &&  params[:database][:db_technology]== "MySQL" 
                  Database.update_tables_in_local_database(@database,data) 
	          @database.update_attributes(:last_sync => Date.today,:oftables => @database.tables.length,:ofrecords => @database.tables.sum('ofrows'),:offields => @database.tables.sum('ofcolumns'))
                  format.html { redirect_to @database, notice: 'Database was successfully created.' }
		else
		@database.destroy
                format.html { redirect_to @database, notice: "#{data}" }
	       end
	    end
      else
        format.html { render action: "new" }
        format.json { render json: @database.errors, status: :unprocessable_entity }

      end
    end
  end

  def update
    @app = sanitized_app(params[:database])
    @database = current_user.organization.databases.find(params[:id])
    @database.app = @app
=begin
  if @database
       if !(@database.db_connection_string === params[:database][:db_connection_string] )
	  render :text =>  "kj" and return
       end
  end
=end
    respond_to do |format|
      if @database.update_attributes(params[:database])
        
        format.html { redirect_to @database, notice: 'Database was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @database.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @database = Database.find(params[:id])
    @database.destroy

    respond_to do |format|
      format.html { redirect_to databases_url }
      format.json { head :no_content }
    end
  end

def search

    @q = current_user.organization.databases.search(params[:q])
    if params[:q]
      @databases = @q.result#result(:distinct  => true).find(:all,:order=>"updated_at DESC")
    end
    
    respond_to do |format|
      format.html
      format.json { head :no_content }
    end
  end


  def database_schema1 #**************synchrnizing database schema***********
     current_database = current_user.organization.databases.find(params[:id])
    data = Database.class_eval("@@synchronize").call("Mysql",current_database.db_connection_string,"update_tables",current_database) if current_database.db_technology == "MySQL" 
    current_database.update_attributes(:last_sync => Date.today)
    #DateTime.now.strftime('%m/%d/%Y')
    if data == "success"
    current_database.update_attributes(:oftables => current_database.tables.length,:ofrecords => current_database.tables.sum('ofrows'),:offields => current_database.tables.sum('ofcolumns'))

    redirect_to databases_url, notice: 'Database was successfully synchronized' 
    else
    redirect_to databases_url, notice: 'Databse was not successfully synchronized'
    end
    
  end

   def database_schema
   @database = current_user.organization.databases.find(params[:id])
=begin
        @conn_str = current_user.organization.databases.find(params[:id])
        @conn_str = @conn_str.db_connection_string
	if @conn_str
        @h_type = get_schema(@conn_str)
        @error = @h_type if @h_type.class == String
       ActiveRecord::Base.establish_connection("mysql2://root:root@localhost/DBMap_development")
        else
          return "connection string error"
       ActiveRecord::Base.establish_connection("mysql2://root:root@localhost/DBMap_development")
        end 
=end
 end
def block_tree_view 

 	respond_to do |format|
		if request.form_data? 
                       @conn_str = current_user.organization.databases.find(params[:id])
	               @show_active =params[:active];@type = params[:theme]
		       p "kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk"
		       p params[:theme]
		       @database = @conn_str
		       p params[:active]
	 		format.js{@database}
		else
                       @conn_str = current_user.organization.databases.find(params[:id])
         		format.html
	 		format.js{@result = "show_active"}
		end
	end

end
 def get_schema(conn_str) #************getting schema*****************
        @conn_str = conn_str 
 	begin
		ActiveRecord::Base.establish_connection(@conn_str)
		h1 =Hash.new
		ActiveRecord::Base.connection.tables.each do |table_name|
			h1[table_name] = ActiveRecord::Base.connection.columns(table_name).map {|c| 
			  h2 = Hash[:name => c.name,:type => c.type.to_s,:limit => c.limit.to_s]
			}
			h1[table_name] << Hash[:count => ActiveRecord::Base.connection.execute("SELECT count(*) count FROM  #{table_name}  ").first,:database => ActiveRecord::Base.connection_config[:database]]
		end
		
		return h1
		rescue Exception => e
	     error_message= "#{e.message}"
	      return "connnection is not established verify host address" if error_message.match("113")
     	  return "connection is not established verify credentials" if error_message.match("111")
          # return "Database not exist in the server "
          #return "Cannot connect with the database"   
         return e.message
 	end
end


def get_sqlite_schema(conn_str)
begin
if !File.exist?("public/sql_dumps/#{conn_str.db_file.file.filename}")
  system "sqlite3 'public#{conn_str.db_file}' .dump | sqlite3 'public/sql_dumps/#{conn_str.db_file.file.filename}'"

end

  	ActiveRecord::Base.connection.close

		
 conn = SQLite3::Database.open("public/sql_dumps/#{conn_str.db_file.file.filename}")
		 conn.results_as_hash = true
   a = conn.execute("SELECT name FROM sqlite_master WHERE type='table'")
   h1 = Hash.new
   a.each do |c|
	    h1[c["name"]] = 1
   end
   
  h1.keys.each do|x|

   stmt = conn.prepare( "select * from '#{x}'" ) 
   h2 = Hash.new()

   h2[:ofcolumns] = stmt.column_count
   h2[:column_types] = stmt.types
     a = Array.new
   h2[:column_types].each do |x|
     a.push(x.delete("a-zA-Z()")) if !x.nil?
     x = x.gsub!(/\(.*\)/, "")  if !x.nil?
   end
   h2[:columns] = stmt.columns
   h2[:sizes] = a
    record = conn.execute("SELECT Count(*) as records FROM '#{x}'")

    h2[:records] = record[0]["records"] if record.any? 
	    h1[x] = h2
   end
return  h1



rescue Exception => e
	return e.message
end

end


def update_sqlite_schema(data,conn_str)
	data.each do |k,v|
		table = conn_str.tables.create(:table_name => k,:ofrows => v[:records],:ofcolumns => v[:ofcolumns],:organization_id => conn_str.organization_id,:user_id =>conn_str.user_id)
		v[:columns].each do |x|

		table.fields.create(:field_name => x,:field_size => v[:sizes][v[:columns].index(x)],:field_type =>v[:column_types][v[:columns].index(x)],:organization_id => conn_str.organization_id,:user_id =>conn_str.user_id)
		end
	end
	return "success"
end
  def dataview
	  #conn = Database.find(params[:id]).db_connection_string
	  #@data = Database.new.dataview(conn)
  	@database  = current_user.organization.databases.find(params[:id])
  end
 def db_data_view

app/views/databases/_db_block_view.html.erb
<style>
 .hovr:hover{
 opacity:0.4
}
.mai{

text-align: center;
position: relative;
margin-top:19px;
height:218px;
padding-top:14px;
margin-right:10px;
border: solid 1px black;
box-shadow: 1px 1px 4px -1px black;
border-radius: 15px 13px 12px 15px;
width:176px;
}
.hovr{
	text-align: center;

	cursor:pointer;
      
}
a:hover {
	
}

.preparing{
	cursor:pointer;
	
}
.db_nam{
color:black;

}
.pre{
float:right;
padding-right:50px;
margin-top:-25px;
}

</style>

          <% i = 0 %>

 
<!-- image block -->
<div style="margin-top:-20px;"> <!-- main  div start  -->

  <div style="float:left;"> <!-- left  div start  -->

<!--- for apps list -->

    <div class="span2 categories well" style="margin-top:20px;padding:6px;margin-left: 0px;">
      <ul class="nav nav-list left_blk" style="height: 200px;">
        <li class="nav-header" style="color:#333;background:whiteSmoke;line-height:27px;padding-left:50px;">Apps</li>
      <% if @apps %>
       <li class="<%= @app.nil? ? "active" : "" %>"><%= link_to "All Apps", databases_path %></li>
        <% @apps.each do |app| %>
         <li class="<%= app == @app ? "active" : "" %>"><%= link_to app.name, databases_path(app: app) %></li>
        <% end %>
      <% end %>
      </ul>
    </div>

<!-- end for apps list -->
 
  </div> <!-- left  div end   -->
  
   <div style="float:right;width:780px;margin-right: -15px;"><!-- right  div start  -->
     <% if @databases.blank? %>
        <div class="well" style="margin-top:20px;margin-left:10px;">
          No Databases found
        </div>
      <% else %>

        <table class="">
        <% @databases.each do |database| %>
          <% if i % 4 == 0 %>
          <tr style="height:230px">
          <% end %>
	  <td style="height:200px;width:200px;  word-wrap: break-word; "> <a  href="<%= database_path(database, :block_view => "a") %> ">
				<div class="mai" >

<div class="hovr">
	<p class="">
	<% if database.image_name.blank? %>
	<img src="../assets/db3.jpg" />
        <% else %>
        <%= image_tag(database.image_name_url(:tiny))  if database.image_name_url  %>
        <% end %>
<span class="db_nam"><b><%= database.db_name%></b></span>
</p>
</div>
</div>
</a>
<br/><br/>

<div style="margin-top:-15px;">
<p >
&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to 'DataView', dataview_databases_path(:id => database.id)  if database.db_technology == "MySQL" %>
&nbsp;&nbsp;&nbsp;
<%= link_to 'Schema', database_schema_path(:id => database.id)  if database.db_technology == "MySQL" %>
<p>&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to 'TreeView', block_tree_view_path(:id => database.id,:treeview =>true)   %>
   <%= simple_form_for :database,:url => url_for(:action=>'pdf_report',:controller=>'databases'), :html => {class: 'form-horizontal pre'}  do |f| %>
        <input type="hidden" name="data_id" value=" <%= database.id %>"/>
		<a class="preparing" id ='<%= database.id %>'>Analysis</a>


<% end %>
</p>
</div>
			</td>
                  <% if i % 4 == 3 %>
          </tr>
          <% end %>
          <% i = i + 1 %>
        <% end %> 
        </table>  
 <% end %> 
<!-- image block ##############################################################-->
</div> <!-- right div end -->
</div><!-- main  div end   -->
         <%#= paginate @patterns %>

 <script>
 $(function() {
	 $('.subm').click(function() { 
		 
	 	var confirmation =confirm("Generate Database Analysis ? ");
if(confirmation == true)
{
		   $('.matter').html("Generating Analysis.please Wait...")
	             $('.pbar').css("display","block");

		 $(this).closest('form').submit();
}
else{
return false;
}
	 });  
});
</script>

app/views/databases/_db_result.html.erb
<script>
 $(document).ready(function (){
	$('.syncing').click(function(e){ 
      	 $('#matter').html("Sync In Progress ...")
	$('#pbar').css("display","block");
 });
 $('.preparing').click(function(e){ 


	 	var confirmation =confirm("Do you want to create pdf report ? ");
		if(confirmation == true)
                {
      	             $('#matter').html("Preparing Document ...")
	             $('#pbar').css("display","block");
                	return true;
                }
		else{
		return false;
		   }
 });
        
 });
</script>
<script>
var w3c=(document.getElementById)?true:false;
var ie=(document.all)?true:false;
var N=-1;

function createBar(w,h,bgc,brdW,brdC,blkC,speed,blocks,count,action){
if(ie||w3c){
var t='<div id="_xpbar'+(++N)+'" style="visibility:visible; position:relative; overflow:hidden; width:'+w+'px; height:'+h+'px; background-color:'+bgc+'; border-color:'+brdC+'; border-width:'+brdW+'px; border-style:solid; font-size:1px;">';
t+='<span id="blocks'+N+'" style="left:-'+(h*2+1)+'px; position:absolute; font-size:1px">';
for(i=0;i<blocks;i++){
t+='<span style="background-color:'+blkC+'; left:-'+((h*i)+i)+'px; font-size:1px; position:absolute; width:'+h+'px; height:'+h+'px; '
t+=(ie)?'filter:alpha(opacity='+(100-i*(100/blocks))+')':'-Moz-opacity:'+((100-i*(100/blocks))/100);
t+='"></span>';
}
t+='</span></div>';
document.write(t);
var bA=(ie)?document.all['blocks'+N]:document.getElementById('blocks'+N);
bA.bar=(ie)?document.all['_xpbar'+N]:document.getElementById('_xpbar'+N);
bA.blocks=blocks;
bA.N=N;
bA.w=w;
bA.h=h;
bA.speed=speed;
bA.ctr=0;
bA.count=count;
bA.action=action;
bA.togglePause=togglePause;
bA.showBar=function(){
this.bar.style.visibility="visible";
}
bA.hideBar=function(){
this.bar.style.visibility="hidden";
}
bA.tid=setInterval('startBar('+N+')',speed);
return bA;
}}

function startBar(bn){
var t=(ie)?document.all['blocks'+bn]:document.getElementById('blocks'+bn);
if(parseInt(t.style.left)+t.h+1-(t.blocks*t.h+t.blocks)>t.w){
t.style.left=-(t.h*2+1)+'px';
t.ctr++;
if(t.ctr>=t.count){
eval(t.action);
t.ctr=0;
}}else t.style.left=(parseInt(t.style.left)+t.h+1)+'px';
}

function togglePause(){
if(this.tid==0){
this.tid=setInterval('startBar('+this.N+')',this.speed);
}else{
clearInterval(this.tid);
this.tid=0;
}}

function togglePause(){
if(this.tid==0){
this.tid=setInterval('startBar('+this.N+')',this.speed);
}else{
clearInterval(this.tid);
this.tid=0;
}}
</script>

<style>
 table { table-layout: fixed; }
 table th, table td { }
</style>
<div>
<h1 style="float:left"> Databases </h1>
<div id="pbar" style="display:none; float:right;  ">
<p id = "matter">  </p>
<script type="text/javascript">
var bar2= createBar(320,15,'white',1,'black','#149BDF',85,7,3);
</script>
</div>
</div>
<table class="table table-striped">  
  <tr>
    <th style="width:20%"><%= sort_link(@q, :db_name, "Database Name") %></th>
    <th  style="width:10%"><%= sort_link(@q, :db_environment, "Environment") %></th>
    <th style="width:10%"><%= sort_link(@q, :db_technology, "Technology") %></th>
    <th  style="width:20%"><%= sort_link(@q, :db_usage, "Usage") %></th>
    <th  style="width:8%"><%= sort_link(@q, :oftables, "#Tables") %></th>
    <th  style="width:8%"><%= sort_link(@q, :offields, "#Fields") %></th>
    <th  style="width:10%"><%= sort_link(@q, :last_sync, "Last Sync") %></th>
    <th style="width:25%"></th>
  </tr>

<% @databases.each do |database| %>
  <tr>
	  <td style="width:15px"> <%= link_to database.db_name,search_tables_path(:q =>{"database_name_cont" =>"#{database.db_name}"}) %> </td>
    <td> <%= database.db_environment %> </td>
    <td> <%= database.db_technology %> </td>
    <td> <%= database.db_usage %> </td>
    <td> <%= number_with_delimiter(database.oftables) %> </td>
    <td> <%= number_with_delimiter(database.offields) %> </td>
    <td> <%= database.last_sync.strftime("%b-%d-%Y") if !database.last_sync.blank? %> </td>

    <td style="width:190px;">
     <%= link_to 'Sync', database_schema1_path(:id => database.id) ,class: 'btn btn-mini btn-primary syncing' %>
      <%= link_to 'DataView', dataview_databases_path(:id => database.id) ,class: 'btn btn-mini btn-primary' if database.db_technology == "MySQL" %>
       <%= simple_form_for :database,:url => url_for(:action=>'pdf_report',:controller=>'databases'), :html => {class: 'form-horizontal preparing'}  do |f| %>
        <input type="hidden" name="data_id" value=" <%= database.id %>"/>
	<%= submit_tag("PDF", :class=> "btn btn-mini btn-primary",:style=>"margin-top:-40px;margin-left:110px;width:40px;") %>

	<% end %>


    </td>
  </tr>
<% end %>
</table>
<br />

app/views/databases/_db_search_form.html.erb
<div class="well"> 
<div id="well simple-search-form">
        <p>  <b>Search Via Tables and fields  </b></p><br/>
<table id ="search_inp" >
<tr> 
  <td>


	<%= search_form_for q,:url => db_search_databases_path, :html => {method: :post, class: 'form-search form-horizontal'}  do |f| %>
        <div class="control-group ">

			
			<div class="control-group">
                          <label ><b>Database&nbsp;&nbsp;</b> </label>	
			  <select id = "db_id"  name = "db_id" onchange ="db_change();" >
			   <option value ="">Please select</option>
			  	<% @db_list.each do |x| %>
			  	<option value="<%= x.id %>"><%= x.db_name %></option>
			  	<% end %>
			  </select>
                        </div>
			<div class="control-group">
                              <div class="form_row" style="display:none;"><br/>
				<label for="theme" ><b>Select :&nbsp;&nbsp;&nbsp;&nbsp;</b> </label>
    					<% [ 'tables', 'fields'].each do |theme| %>
     					 <%= radio_button_tag 'theme', theme, @theme == theme %>
                                              <%= theme.humanize %>
    				<% end %>
				</div> 
				
		  	 </div>
	</div>


                  <fieldset>
                       <!-- fields goes here -->

			<div style="display:none;" class="desc" id="tables">
                        <%= f.text_field :tables_table_name_cont, class: "input-medium search-query" %>
		            <button type="submit" class="btn">
			            Search Tables
		            </button></div>
			<div style="display:none;" class="desc" id="fields">
                        <%= f.text_field :tables_database_name_cont, class: "input-medium search-query" %>
		            <button type="submit" class="btn">
			            Search Fields
		            </button></div>
                </fieldset>
         <% end %>
</td>
</tr>
</table>
</div>
</div>
<script type="text/javascript">
 function db_change(){
	var selectVal = $('#db_id :selected').val();
	if (selectVal !=""){
	$('.form_row').css("display","block");
        if($('#theme_tables').is(':checked')) { $("#tables").show(); }
	if($('#theme_fields').is(':checked')) { $("#fields").show(); }
}
else{
$("div.desc").hide();

$('.form_row').css("display","none");

}

    }
$(document).ready(function(){ 
 $('#search_inp').find('input:text').val('');    
    $("input[name$='theme']").click(function() {

        var test = $(this).val();
        $("div.desc").hide();
        $("#"+test).show();
        

	

    }); 
    $("input[name='theme']").change(function() {
            if ($("input[name='theme']:checked").val() == 'tables')
                $("#q_tables_database_name_cont").val("");
            else
                $("#q_tables_table_name_cont").val("");
        });
});
</script>

app/views/databases/_menu.html.erb
<ul class="nav nav-tabs">
  <li class="<%= action_active('index') %>">
    <%= link_to databases_path do %>
        <i class="icon-list-alt"></i>
        Index
    <% end %>
  </li>
  
  <li class="<%= action_active('new') %>">
    <%= link_to new_database_path do %>
      <i class="<%= green_icon %>"></i>
      Create New Database
    <% end %>
  </li>

</ul>

app/views/databases/_options.html.erb
  <%#= stylesheet_link_tag    "application", :media => "all" %>
<%#= javascript_include_tag "application" %>
<style>
	.im{
		width:100px;
		margin-top: 24px;
                margin-left: 75px;
	}
			#view_report{
				margin-top: 45px;
margin-left: 111px;}

</style>
<script>
 $(document).ready(function (){
$('.type').attr('checked', 'checked');
$('.clo').click(function(e){
	 var sync_confirmation =confirm("Generating the Analysis ? ");
	 if(sync_confirmation == true)
	 {
           $('#view_report').submit();
  	   $('#show_form').hide()
           $('#cbar').css('display', 'block');
        } 
	else{
		return false
	
	}
});
 });
</script>

<div id="cbar" style="display:none;margin-top:34px;margin-left:65px   ">
	<span style="color:black;margin-top:10px;margin-left:10px" >Generating Analysis Please wait ...</span>
 <img src="/assets/loader.gif" class="im" />
</div>

<div id="show_form">
<%= form_for(:at,  :url=> url_for(view_report_path),:method => :get, :html => {  :id => "view_report" } ) do |f| %>
	<%#= form_for(:at,  :controller=> 'databases',:action => 'view_report',:method => :post, :html => {  :id => "view_report" } ) do |f| %>
		<input type="hidden"  value=<%= @database %>  name="put_datas"></input>
	<p><input type="checkbox" value="type"  class = "" name="type"  >&nbsp;Include Tables By Type</input></p>
	<p><input type="checkbox" value="fields"  class = "" name="fields"  >&nbsp;Include Fields List</input></p>
	<p><input type="checkbox" value="data"  class = "" name="data"  >&nbsp;Include Data Samples</input></p>
	<p><input type="checkbox" value="not_used"  class = "type" name="not_used" >&nbsp;Include Tables that are not used</input></p>
	<p><input type="button" class="clo" value="Submit"></input></p>
<%end%>
</div>

app/views/databases/_tree_table1.html.erb
<table>
<tr class="<%= @conn_str.id %>">
	<td style="" class="<%= @conn_str.id %>"> 
       <ul id="browser" class="filetree treeview-famfamfam " >
	<li> <span class="folder"><%= @conn_str.db_name %></span>
	<ul>
	<% @tables.each do |d| %>
 		<li > <span class="folder"><%= d.table_name %></span>
                 		<ul>
			<% d.fields.sort_by{ |i| i[:field_name]}.each do |f| %>
			<li><span class="file"><%=f.field_name %></span></li>
			<% end %>
			</ul>
                </li>
       <% end %>
       </ul>
        </li>

       </ul>
</td>
</tr>
</table>

app/views/databases/block_tree_view.js.erb
$('#chang').html(
		"<%= j render(:partial => 'databases/schema',:locals =>{:imp => "hj"}) %>"

		)

app/views/databases/edit.html.erb
<%= render 'form' %>

app/views/databases/show.html.erb
<%= render :partial => "menu" %>
<p> 
<b> Database Name:</b>
<%= @database.db_name %>
</p><br/>
<p> 
<b> Environment:</b>
<%= @database.db_environment %>
</p><br/>
<p> 
<b> Hosting:</b>
<%= @database.db_hosting %>
</p><br/>
<b> App Name:</b>
<%= @database.app.try(:name) %>
</p><br/>
<p> 
<b> Technology:</b>
<%= @database.db_technology %>
</p><br/>
<p> 
<b> Connection String:</b>
<%= @database.db_connection_string %>
</p><br/> 
<p> 
<b> Version:</b>
<%= @database.db_version %>
</p><br/>
<p> 
<b> Active:</b>
<%= @database.db_active? ? 'Yes' : 'No' %>
</p><br/>
<p> 
<b> Usage:</b>
<%= simple_format(@database.db_usage) %>
</p><br/>

<%= link_to 'Edit', edit_database_path(@database),class: 'btn btn-primary btn-danger' %> 

<%= link_to 'Destroy', @database, confirm: 'Are you sure?', method: :delete ,class: 'btn btn-danger  btn-primary  ' %>
<%= link_to 'Back', databases_path,class: 'btn btn-default' %>