config/routes.rb
DBMap::Application.routes.draw do
  resources :apps

  resources :environments

  resources :hostings do
    collection do
      match 'search' => 'hostings#search', :via => [:get, :post], :as => :search
    end
  end 
   resources :databases do 
 collection do
      match 'search' => 'databases#search', :via => [:get, :post], :as => :search
      match 'dataview' => 'databases#dataview',:via => [:get,:post]
      match 'db_search' => 'databases#db_search',:via => [:get,:post], :as => :db_search
     match '/db_search_view' => "databases#db_search_view"
    end

  end
   post '/options' => 'databases#options'
     match 'view_report' => 'databases#view_report'

   resources :fields do
    collection do
      match 'search' => 'fields#search', :via => [:get, :post], :as => :search
    end
   end 
   resources :tables do
    collection do
      match 'search' => 'tables#search', :via => [:get, :post], :as => :search
    end
   end 
  resources :schemas
  resources :pages
  post "pdf_report"=>"databases#pdf_report"
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login' => 'sessions#new', as: :login
  get 'signup' => 'users#new', as: :signup
  get 'account' => 'users#edit', as: :account
  get '/admin' => 'admin/categories#index'
  match '/download_single_pattern/:id' => "patterns#download_single_pattern"
  match '/download_patterns' => "patterns#download_patterns"
  match '/database_schema' => "databases#database_schema"
  match '/block_tree_view' => "databases#block_tree_view"
  match '/database_schema1' => "databases#database_schema1"
  resources :users, except: :destroy
  resources :sessions, only: [:new, :create, :destroy]
  resources :patterns
match '/db_data_view' => "databases#db_data_view"

  namespace :admin do
    resources :users, except: [:show]
    resources :categories do
      collection { post :sort }
    end
    root to: "home#index"  
  end
  root to: "home_page#index"
  match '/privacy' => 'pages#privacy'
  match '/contact_us' => 'pages#new'
  match '/legal'=> 'pages#legal'
  match '/pricing' => 'pages#pricing'

end

app/models/field.rb
class Field < ActiveRecord::Base
  attr_accessible :database, :description, :environment, :field_name, :field_size, :field_type, :validation_edit,:organization_id,:user_id,:database_name,:table_name,:short_description
  validates :short_description,:length => {:maximum =>60} 
  belongs_to :user
  belongs_to :organization
  belongs_to :database
  belongs_to :fieldable, :polymorphic =>true
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  before_filter :authorize
  # GET /fields
  # GET /fields.json
  def index
    @q = current_user.organization.fields.search(params[:q])
   @fields = @q.result.page(params[:page]).per(30)
#(:distinct  => true).find(:all,:order=>"updated_at DESC")
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fields }
    end
  end

  # GET /fields/1
  # GET /fields/1.json
  def show
    @field = Field.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @field }
    end
  end

  # GET /fields/new
  # GET /fields/new.json
  def new
    @field = Field.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @field }
    end
  end

  # GET /fields/1/edit
  def edit
    @field = Field.find(params[:id])
  end

  # POST /fields
  # POST /fields.json
  def create
    @field = Field.new(params[:field])
    @field.organization = current_user.organization
    @field.user = current_user

    respond_to do |format|
      if @field.save
        format.html { redirect_to @field, notice: 'Field was successfully created.' }
        format.json { render json: @field, status: :created, location: @field }
      else
        format.html { render action: "new" }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fields/1
  # PUT /fields/1.json
  def update
    @field = Field.find(params[:id])

    respond_to do |format|
      if @field.update_attributes(params[:field])
        format.html { redirect_to @field, notice: 'Field was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fields/1
  # DELETE /fields/1.json
  def destroy
    @field = current_user.organization.fields.find(params[:id])
    @field.destroy

    respond_to do |format|
      format.html { redirect_to fields_url }
      format.json { head :no_content }
    end
  end

  def search
   
    @q = current_user.organization.fields.search(params[:q])
    if params[:q]
      @fields = @q.result(:distinct  => true).find(:all,:order=>"updated_at DESC")
    end
    
    respond_to do |format|
      format.html
      format.json { head :no_content }
    end
  end

end

app/views/fields/_form.html.erb
<%= simple_form_for(@field, :html=>{:multipart => true, class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
 

   <%= f.input :database_name,:readonly => true %>
<div class="control-group "><label class="string optional control-label" >Table</label><div class="controls"><input class="string optional readonly"  name="" readonly="readonly" size="50" type="text" value= <%=Field.find(@field.id).fieldable.table_name%>></div></div>
   <%= f.input :environment %>
 <%= f.input :short_description,:label => 'Description', input_html: {rows: '2',cols: '2', class: 'span6'} %>
    <%#= f.input :field_name %>
    <%= f.input :validation_edit %>
   <%#= f.input :field_type %>
   <%#= f.input :field_size %>
 <%= f.input :description,:label => 'Long Description', input_html: {rows: '5',cols: '3', class: 'span9'} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/fields/_menu.html.erb
<ul class="nav nav-tabs">
  <li class="<%= action_active('index') %>">
    <%= link_to fields_path do %>
        <i class="icon-list-alt"></i>
        Index
    <% end %>
  </li>

  <li class="<%= action_active('new') %>">
    <%= link_to new_field_path do %>
      <i class="<%= green_icon %>"></i>
      Create New Record
    <% end %>
  </li>
</ul>

app/views/fields/_search_form.html.erb
<div id="simple-search-form">
  <%= search_form_for q,:url => search_fields_path, :html => {method: :post, class: 'well form-search'}  do |f| %>
  <fieldset>
    <%= f.text_field :environment_or_description_or_field_type_or_table_name_or_database_name_or_field_name_cont, class: "input-medium search-query" %>
    <button type="submit" class="btn">Search</button> &nbsp;&nbsp;
     <a href="#" id="advance-search">Advance</a>
  <% end %>
  </fieldset>
</div>

<div id="advance-search-form" style="display: none">
  <%= search_form_for q,:url => search_fields_path, :html => {method: :post, class: 'form-horizontal'}  do |f| %>
  <fieldset>
  <legend>Search Fields</legend>
  <div class="control-group">
    <%= f.label :environment_cont, "Environment", class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :environment_cont %>
    </div>
  </div>
  
  
  <div class="control-group">
    <%= f.label :database_cont, "Database", class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :database_name_cont %>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label :field_name_cont, "Field Name", class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :field_name_cont %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :validation_edit_cont, "Validation/Edit", class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :validation_edit_cont %>
    </div>
  </div>
<div class="control-group">
    <%= f.label :field_type_cont, "Type", class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :field_type_cont %>
    </div>
  </div>
<div class="control-group">
    <%= f.label :field_size_eq, "Size", class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :field_size_eq %>
    </div>
  </div>

 
  
  <div class="form-actions">
    <%= f.submit class: 'btn btn-primary' %>
    <input type="reset" class='btn'></input>
    <a href="#" id="advance-search">Simple</a>
  </div>  
  </fieldset>
  <% end %>
</div>

app/views/fields/edit.html.erb
<h1>Editing field</h1>

<%= render 'form' %>

<%= link_to 'Show', @field %> |
<%= link_to 'Back', fields_path %>

app/views/fields/index.html.erb
<%#= render :partial => "menu" %>
<% if !@fields.nil? %>
<%= render :partial => "fields/search_form", locals: {q: @q} %>
<%end %>
<% if @fields.blank? %>
  <div class="well">You don't currently have any fields </div>
<% else %>
<h1>Fields</h1>

<table class="table table-striped" >
  <tr>
    <th><%= sort_link(@q,:database_name," Database Name") %></th>
    <th><%= sort_link(@q,:table_name," Table") %></th>
  <th><%= sort_link(@q, :field_name, "FieldName") %></th>

 <th><%= sort_link(@q, :field_type, "Type") %></th>
    <th><%= sort_link(@q, :field_size, "Size") %></th>
    <th><%= sort_link(@q, :environment, "Environment") %></th>
 <th><%= sort_link(@q, :description, "Description") %></th>

    <th></th>
    <th></th>
  </tr>
  <% @fields.each do |field| %>
  <tr>
    <td><%= field.database_name %></td>
    <td><%= field.table_name %></td>
    <td><%= field.field_name %></td>
    <td><%= field.field_type %></td>
   <td><%= field.field_size %></td>
    <td><%= field.environment %></td>
    
    <td><%= truncate(field.description,:length=>30) %></td>
    
  
    <td>
   <%= link_to 'Show', field, class: 'btn btn-mini' %>
   <%= link_to 'Edit', edit_field_path(field), class: 'btn btn-mini' %>
    </td>
    <td></td><td></td>
  </tr>
<% end %>
</table>
<%= paginate @fields  %>
<% end %>

app/views/fields/new.html.erb
<%= render :partial => "menu" %>

<%= render 'form' %>

<%#= link_to 'Back', fields_path %>

app/views/fields/search.html.erb
<%= render :partial => "search_form", locals: {q: @q} %>
<div id="search-result">
  <% if @fields.blank? %>
    <% if params[:q] %>
       <p class="well">No records found</p>
	    <% else %>
		    <p>Your search does not generate a result</p>
    <% end %>
  <% else %>
  <div style="float:right;margin-right:20px;"><% unless @fields.blank? %>[<%= @fields.count %>] Records Found<% end %></div>
<br/>
<table class="table table-striped" >
  <tr>
    <th><%= sort_link(@q,:database_name," Database Name") %></th>
    <th><%= sort_link(@q,:table_name," Table") %></th>
  <th><%= sort_link(@q, :field_name, "FieldName") %></th>

 <th><%= sort_link(@q, :field_type, "Type") %></th>
    <th><%= sort_link(@q, :field_size, "Size") %></th>
    <th><%= sort_link(@q, :environment, "Environment") %></th>
 <th><%= sort_link(@q, :description, "Description") %></th>

    <th></th>
    <th></th>
  </tr>
  <% @fields.each do |field| %>
  <tr>
    <td><%= field.database_name %></td>
    <td><%= field.table_name %></td>
    <td><%= field.field_name %></td>
    <td><%= field.field_type %></td>
   <td><%= field.field_size %></td>
    <td><%= field.environment %></td>
    
    <td><%= truncate(field.description,:length=>30) %></td>
    
  
    <td>
   <%= link_to 'Show', field, class: 'btn btn-mini' %>
   <%= link_to 'Edit', edit_field_path(field), class: 'btn btn-mini' %>
    </td>
    <td></td><td></td>
  </tr>
<% end %>
</table>

<% end %>
</div>

app/views/fields/show.html.erb
<p>
  <b>Environment:</b>
  <%= @field.environment %>
</p>

<p>
  <b>Table:</b>
  <%= Table.find(@field.fieldable_id).table_name  %>
</p>
<p>
  <b>Field name:</b>
  <%= @field.field_name %>
</p>

<p>
  <b>Validation edit:</b>
  <%= @field.validation_edit %>
</p>

<p>
  <b>Type:</b>
  <%= @field.field_type %>
</p>

<p>
  <b>Size:</b>
  <%= @field.field_size %>
</p>


<p>
  <b>Description:</b>
  <%= @field.description %>
</p>



<%= link_to 'Edit', edit_field_path(@field), class: 'btn' %> 
<%#= link_to 'Delete', field_path(@field), method: :delete, confirm: "Are you sure?", class: 'btn btn-danger' %>
<%= link_to 'Back', fields_path , class: 'btn'%>